// This code was generated by TouchTools3 v3.0.24.0 on 1/31/2020 3:56:32 PM for use with CustomMeas v7386
#include "API_CustomMeas.h"

CustomMeasGlobalInfo_t GlobalInfo =
{
  .Enable = 1,
  .FrameMillisLSB = 0x0A, // 10 ms
  .FrameMillisMSB = 0x00,
  .Persist = 0,
  .Restore = 0,
  .POR_Enable = 1,
  .LowPowerMode = 0,
};

CustomMeasGroupInfo_t GroupInfoArray[5] =
{
  { //Group 0
    .Mode = 1, // Self_V2V
    .Calibration = 0x81, // Background
    .FrameBetweenCompsLSB = 0xEE, // 750
    .FrameBetweenCompsMSB = 0x2,
    .NegativeThresholdLSB = 0xB5, // -75
    .NegativeThresholdMSB = 0xFF,
    .SpeedThresholdLSB = 0x2C, // 300
    .SpeedThresholdMSB = 0x1,
    .ActivityThresholdLSB = 0x58, // 600
    .ActivityThresholdMSB = 0x2,
    .ActivityTimeoutLSB = 0x96, // 150
    .ActivityTimeoutMSB = 0x0,
  },
  { //Group 1
    .Mode = 1, // Self_V2V
    .Calibration = 0x80, // SnapShot
    .FrameBetweenCompsLSB = 0xEE, // 750
    .FrameBetweenCompsMSB = 0x2,
    .NegativeThresholdLSB = 0xB5, // -75
    .NegativeThresholdMSB = 0xFF,
    .SpeedThresholdLSB = 0x2C, // 300
    .SpeedThresholdMSB = 0x1,
    .ActivityThresholdLSB = 0x58, // 600
    .ActivityThresholdMSB = 0x2,
    .ActivityTimeoutLSB = 0x96, // 150
    .ActivityTimeoutMSB = 0x0,
  },
  { //Group 2
    .Mode = 1, // Self_V2V
    .Calibration = 0x80, // SnapShot
    .FrameBetweenCompsLSB = 0xEE, // 750
    .FrameBetweenCompsMSB = 0x2,
    .NegativeThresholdLSB = 0xB5, // -75
    .NegativeThresholdMSB = 0xFF,
    .SpeedThresholdLSB = 0x2C, // 300
    .SpeedThresholdMSB = 0x1,
    .ActivityThresholdLSB = 0x58, // 600
    .ActivityThresholdMSB = 0x2,
    .ActivityTimeoutLSB = 0x96, // 150
    .ActivityTimeoutMSB = 0x0,
  },
  { //Group 3
    .Mode = 1, // Self_V2V
    .Calibration = 0x80, // SnapShot
    .FrameBetweenCompsLSB = 0xEE, // 750
    .FrameBetweenCompsMSB = 0x2,
    .NegativeThresholdLSB = 0xB5, // -75
    .NegativeThresholdMSB = 0xFF,
    .SpeedThresholdLSB = 0x2C, // 300
    .SpeedThresholdMSB = 0x1,
    .ActivityThresholdLSB = 0x58, // 600
    .ActivityThresholdMSB = 0x2,
    .ActivityTimeoutLSB = 0x96, // 150
    .ActivityTimeoutMSB = 0x0,
  },
  { //Group 4
    .Mode = 1, // Self_V2V
    .Calibration = 0x80, // SnapShot
    .FrameBetweenCompsLSB = 0xEE, // 750
    .FrameBetweenCompsMSB = 0x2,
    .NegativeThresholdLSB = 0xB5, // -75
    .NegativeThresholdMSB = 0xFF,
    .SpeedThresholdLSB = 0x2C, // 300
    .SpeedThresholdMSB = 0x1,
    .ActivityThresholdLSB = 0x58, // 600
    .ActivityThresholdMSB = 0x2,
    .ActivityTimeoutLSB = 0x96, // 150
    .ActivityTimeoutMSB = 0x0,
  },
};

CustomMeasInfo_t MeasInfoArray[] =
{
  { // Measurement 0
    .Control = 0x80,
    .ElectrodeStates =
    {
      0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 
      0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 
      0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 
    },
    .Gain = 3,
    .GlobalOffset = 0x1F, // 31
    .ChannelOffsetMultiplier = 0,
    .ChannelOffsets = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, },
    .ToggleFrequency = 19,
    .ApertureLength = 39,
    .Waveform = 0,
    .ADCChannelMaskLSB = 0xFF,
    .ADCChannelMaskMSB = 0xFF,
  },
  { // Measurement 1
    .Control = 0x80,
    .ElectrodeStates =
    {
      0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 
      0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 
      0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 
    },
    .Gain = 3,
    .GlobalOffset = 0x1F, // 31
    .ChannelOffsetMultiplier = 0,
    .ChannelOffsets = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, },
    .ToggleFrequency = 19,
    .ApertureLength = 39,
    .Waveform = 0,
    .ADCChannelMaskLSB = 0xFF,
    .ADCChannelMaskMSB = 0xFF,
  },
  { // Measurement 2
    .Control = 0x80,
    .ElectrodeStates =
    {
      0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 
      0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 
      0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 
    },
    .Gain = 3,
    .GlobalOffset = 0x1F, // 31
    .ChannelOffsetMultiplier = 0,
    .ChannelOffsets = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, },
    .ToggleFrequency = 19,
    .ApertureLength = 39,
    .Waveform = 0,
    .ADCChannelMaskLSB = 0xFF,
    .ADCChannelMaskMSB = 0xFF,
  },
};
